%% 生成JPG
% sourcePath = 'D:\科研\MSTAR\MSTAR-PublicClutter-CD1\MSTAR_PUBLIC_CLUTTER_CD1\CLUTTER\15_DEG\';
% targetPath = 'D:\科研\MSTAR\MSTAR-PublicClutter-CD1\MSTAR_PUBLIC_CLUTTER_CD1\CLUTTERJPG\15_DEG\';
% MSTAR2JPG(sourcePath,targetPath)
sourcePath ='D:\科研\MSTAR\MSTAR-PublicTargetChips-T72-BMP2-BTR70-SLICY\MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY\TARGETS\TEST\15_DEG\BMP2\SN_9563\';
targetPath ='D:\科研\MSTAR\MSTAR-PublicTargetChips-T72-BMP2-BTR70-SLICY\MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY\TARGETSJPG\TEST\15_DEG\BMP2\SN_9563\';
MSTAR2JPG(sourcePath,targetPath)
% sourcePath2 =' D:\matlabcode\MSTAR\Graduation Project\MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY\TARGETS\TEST\15_DEG\T72\SN_812\';
% targetPath2 = 'D:\matlabcode\MSTAR\Graduation Project\MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY\TARGETSJPG\TEST\15_DEG\T72\SN_812\';
% MSTAR2JPG(sourcePath2,targetPath2)


